language: go
go:
    - 1.x
    - master
env:
    - GO111MODULE=on
os:
    - linux
    - osx
    - windows
matrix:
    allow_failures:
        - os: windows
script: 
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmake test ; fi
    - if [ "$TRAVIS_OS_NAME" != "windows" ]; then make test ; fi
