name: Notify
on: [issues]
jobs:
  notify:
    runs-on: ubuntu-latest
    name: Notify Slack channel about a new issue
    steps:
    - name: Notify
      env:
          URL: ${{secrets.SLACK_NOTIFICATION_URL}}
          ACTION: ${{github.event.action}}
          ISSUE_URL: ${{github.event.issue.html_url}}
          ISSUE_TITLE: ${{github.event.issue.title}}
      run: curl -s ${URL} -d '{"text":"Issue <'${ISSUE_URL}'|'"${ISSUE_TITLE}"'> has been '${ACTION}'"}'
