name: Notify
on: 
  pull_request:
      types: [labeled, unlabeled]
  issues:
      types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
jobs:
  notify:
    runs-on: ubuntu-latest
    name: Notify Slack channel about a new issue
    steps:
    - name: Notify using custom action
      uses: makkes/action-notify@master
      with:
        slack-url: ${{secrets.SLACK_NOTIFICATION_URL}}
