name: Notify
on: [issues,pull_request]
jobs:
  notify:
    runs-on: ubuntu-latest
    name: Notify Slack channel about a new issue
    steps:
    - name: Notify using custom action
      uses: makkes/action-notify@master
      with:
          slack-url: ${{secrets.SLACK_NOTIFICATION_URL}}
