name: Notify
on: [issues]
jobs:
  notify:
    runs-on: ubuntu-latest
    name: Notify Slack channel about a new issue
    steps:
    - name: Notify
      env:
          URL: ${{secrets.SLACK_NOTIFICATION_URL}}
          EVENT: ${{toJson(github)}}
      run: curl ${URL} -d '{"text":"'${EVENT}'"}'
