on:
  release:
    types: [published]
name: Release
jobs:
    generate:
        name: Create CLI binaries
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the repository
            uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
          - name: Generate artifacts
            uses: skx/github-action-build@5ca2e55b7ba4583d27b0e4c256685dd7fffb4acf
          - name: Upload artifacts
            uses: skx/github-action-publish-binaries@cafb819f9432619c3331782ffbbb752f1e2be626
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                args: 'build/gitlab_*'
