name: Test
on: [push]
jobs:
  test:
    strategy:
        matrix:
            go: ['1.x']
            os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Test Go ${{ matrix.go }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@94d077c24971944d312dd9197c1bdfba62b39878
    - uses: actions/setup-go@75259a5ae02e59409ee6c4fa1e37ed46ea4e5b8d
      with:
          go-version: ${{ matrix.go }}
    - name: Get golangci-lint
      run: |
          export GO111MODULE=off
          go get github.com/golangci/golangci-lint/cmd/golangci-lint
    - name: Debug
      run: |
          env
          command -v go
          echo $GOPATH
          go env GOPATH
          go env GOBIN
          pwd
    - name: Run unit tests
      run: make lint test
